// src/constants/huntingGrounds.ts
import type { HuntingContent, JobCategory } from "../types/hunting";

export const JOB_CATEGORIES: JobCategory[] = [
  "전사",
  "마법사",
  "궁수",
  "도적",
  "해적",
  "시그너스 기사단",
  "영웅",
  "레지스탕스",
  "노바",
  "제로",
  "키네시스",
  "카데나",
  "아델",
  "카인",
  "라라",
  "칼리",
];

export const HUNTING_CONTENTS: HuntingContent[] = [
  // 초급 사냥터 (1-50)
  {
    id: "perion-dungeon",
    name: "페리온 던전",
    type: "hunting",
    map: "페리온",
    levelRange: "10-30",
    minLevel: 10,
    maxLevel: 30,
    expEfficiency: 6,
    mesoEfficiency: 5,
    difficulty: "Easy",
    playStyle: "both",
    isZeroBurn: true,
    jobRecommendation: ["전사", "궁수"],
    monsters: ["주니어 발록", "아이언 보어", "스톤 골렘"],
    description:
      "초보자들이 레벨업하기 좋은 안전한 사냥터입니다. 쩔받는 용 적용으로 빠른 성장이 가능합니다.",
    tips: [
      "체력이 낮은 몬스터들로 구성되어 있어 초보자에게 적합",
      "쩔받는 용 적용으로 경험치 2배",
      "근거리 공격 캐릭터에게 유리한 맵 구조",
    ],
  },
  {
    id: "ant-tunnel",
    name: "개미굴",
    type: "hunting",
    map: "슬리피우드",
    levelRange: "30-50",
    minLevel: 30,
    maxLevel: 50,
    expEfficiency: 8,
    mesoEfficiency: 7,
    difficulty: "Normal",
    playStyle: "both",
    isZeroBurn: true,
    jobRecommendation: ["전사", "도적", "해적"],
    monsters: ["개미", "머쉬맘", "좀비 머쉬맘"],
    description: "중간 레벨대에서 효율적인 사냥이 가능한 곳입니다.",
    tips: [
      "넓은 맵으로 여러 파티 동시 사냥 가능",
      "메소 드랍률이 좋음",
      "쩔받는 용 적용으로 빠른 레벨업",
    ],
  },

  // 파티퀘스트
  {
    id: "kerning-pq",
    name: "커닝 파티퀘스트",
    type: "partyquest",
    map: "커닝시티",
    levelRange: "21-30",
    minLevel: 21,
    maxLevel: 30,
    expEfficiency: 7,
    mesoEfficiency: 4,
    difficulty: "Easy",
    playStyle: "party",
    isZeroBurn: true,
    jobRecommendation: ["모든 직업"],
    monsters: ["슬라임", "주황버섯", "리본 돼지"],
    description: "초보자를 위한 첫 파티퀘스트 경험을 제공합니다.",
    tips: [
      "3-6인 파티 구성 필요",
      "쩔받는 용 적용",
      "협동 플레이 학습 가능",
      "보상으로 추가 경험치 획득",
    ],
    timeRequired: "15-25분",
  },
  {
    id: "ludi-pq",
    name: "루디브리엄 파티퀘스트",
    type: "partyquest",
    map: "루디브리엄",
    levelRange: "35-50",
    minLevel: 35,
    maxLevel: 50,
    expEfficiency: 8,
    mesoEfficiency: 5,
    difficulty: "Normal",
    playStyle: "party",
    isZeroBurn: true,
    jobRecommendation: ["모든 직업"],
    monsters: ["블록 골렘", "라이온킹"],
    description: "중급자를 위한 파티퀘스트로 좋은 경험치를 제공합니다.",
    tips: [
      "4-6인 파티 구성 권장",
      "퍼즐과 협동이 필요한 스테이지",
      "보스 라이온킹 처치 필요",
    ],
    timeRequired: "20-30분",
  },
  {
    id: "romeo-juliet-pq",
    name: "로미오와 줄리엇 PQ",
    type: "partyquest",
    map: "루디브리엄",
    levelRange: "70-120",
    minLevel: 70,
    maxLevel: 120,
    expEfficiency: 9,
    mesoEfficiency: 6,
    difficulty: "Normal",
    playStyle: "party",
    isZeroBurn: false,
    jobRecommendation: ["모든 직업"],
    monsters: ["파티퀘스트 몬스터"],
    description:
      "파티원들과 함께 즐기며 경험치를 얻을 수 있는 파티퀘스트입니다.",
    tips: [
      "4-6인 파티 구성 필요",
      "1일 1회 제한",
      "보상으로 추가 경험치 획득",
      "로미오와 줄리엣 스토리 진행",
    ],
    timeRequired: "30-45분",
  },

  // 중급 사냥터 (50-150)
  {
    id: "toy-factory",
    name: "장난감 공장",
    type: "hunting",
    map: "루디브리엄",
    levelRange: "50-70",
    minLevel: 50,
    maxLevel: 70,
    expEfficiency: 7,
    mesoEfficiency: 6,
    difficulty: "Normal",
    playStyle: "both",
    isZeroBurn: false,
    jobRecommendation: ["마법사", "궁수"],
    monsters: ["토이 트루퍼", "플레인", "로보"],
    description: "장거리 공격 캐릭터에게 유리한 사냥터입니다.",
    tips: [
      "넓은 맵으로 원거리 공격에 유리",
      "토이 계열 몬스터들",
      "마법사와 궁수 추천",
    ],
  },
  {
    id: "aquarium",
    name: "아쿠아리움",
    type: "hunting",
    map: "아쿠아로드",
    levelRange: "120-140",
    minLevel: 120,
    maxLevel: 140,
    expEfficiency: 9,
    mesoEfficiency: 8,
    difficulty: "Normal",
    playStyle: "solo",
    isZeroBurn: false,
    jobRecommendation: ["마법사", "궁수", "도적"],
    monsters: ["옥토퍼스", "플로라", "씨 위치"],
    description: "120대 구간에서 가장 인기 있는 솔로 사냥터입니다.",
    tips: [
      "솔로 사냥에 최적화",
      "넓은 맵으로 쾌적한 사냥",
      "수중 몬스터들로 구성",
    ],
  },

  // 고급 사냥터 (150+)
  {
    id: "future-city",
    name: "리버스 시티",
    type: "hunting",
    map: "미래 도시",
    levelRange: "160-190",
    minLevel: 160,
    maxLevel: 190,
    expEfficiency: 8,
    mesoEfficiency: 9,
    difficulty: "Normal",
    playStyle: "both",
    isZeroBurn: false,
    jobRecommendation: ["전사", "해적", "영웅"],
    monsters: ["로보트", "사이버그", "베르가못"],
    description: "메소 파밍에 특화된 사냥터입니다.",
    tips: [
      "높은 메소 드랍률",
      "넓은 맵으로 파티 사냥 가능",
      "미래형 로봇 몬스터들",
    ],
  },
  {
    id: "arcana",
    name: "드래곤 라이더 (아르카나)",
    type: "hunting",
    map: "아르카나",
    levelRange: "225-250",
    minLevel: 225,
    maxLevel: 250,
    expEfficiency: 10,
    mesoEfficiency: 9,
    difficulty: "Hard",
    playStyle: "solo",
    isZeroBurn: false,
    jobRecommendation: ["영웅", "노바", "시그너스 기사단"],
    monsters: ["드래곤 라이더", "스피릿 세이비어"],
    description: "고레벨 구간의 최고 효율 사냥터입니다.",
    tips: [
      "아케인포스 540 이상 필요",
      "높은 딜량 요구",
      "최고 경험치 효율",
      "솔로 사냥 전용",
    ],
  },

  // 보스
  {
    id: "easy-zakum",
    name: "자쿰 (쉬움)",
    type: "boss",
    map: "자쿰의 동굴",
    levelRange: "50-120",
    minLevel: 50,
    maxLevel: 120,
    expEfficiency: 8,
    mesoEfficiency: 7,
    difficulty: "Easy",
    playStyle: "both",
    isZeroBurn: false,
    jobRecommendation: ["모든 직업"],
    monsters: ["자쿰"],
    description:
      "초보자도 도전할 수 있는 쉬운 보스로 좋은 경험치를 제공합니다.",
    tips: [
      "1일 2회 가능",
      "파티 구성 시 더 안전",
      "좋은 장비 드랍 가능",
      "자쿰의 투구 획득 가능",
    ],
    timeRequired: "10-20분",
  },
  {
    id: "normal-horntail",
    name: "혼테일 (보통)",
    type: "boss",
    map: "동굴 입구",
    levelRange: "120-160",
    minLevel: 120,
    maxLevel: 160,
    expEfficiency: 9,
    mesoEfficiency: 8,
    difficulty: "Normal",
    playStyle: "both",
    isZeroBurn: false,
    jobRecommendation: ["모든 직업"],
    monsters: ["혼테일"],
    description: "중급자를 위한 보스로 다양한 보상을 제공합니다.",
    tips: [
      "1일 1회 도전 가능",
      "파티 추천 (최대 6인)",
      "혼테일 목걸이 드랍",
      "선행퀘스트 필요",
    ],
    timeRequired: "15-30분",
  },
  {
    id: "easy-pink-bean",
    name: "핑크빈 (쉬움)",
    type: "boss",
    map: "신전",
    levelRange: "160-200",
    minLevel: 160,
    maxLevel: 200,
    expEfficiency: 9,
    mesoEfficiency: 8,
    difficulty: "Normal",
    playStyle: "both",
    isZeroBurn: false,
    jobRecommendation: ["모든 직업"],
    monsters: ["핑크빈"],
    description: "고레벨 보스 입문용으로 좋은 보스입니다.",
    tips: [
      "1일 1회 도전 가능",
      "높은 경험치 보상",
      "핑크빈 컵 드랍 가능",
      "파티 구성 권장",
    ],
    timeRequired: "20-40분",
  },
];

export const DIFFICULTY_COLORS = {
  Easy: "bg-green-500/20 text-green-400 border-green-500/30",
  Normal: "bg-yellow-500/20 text-yellow-400 border-yellow-500/30",
  Hard: "bg-red-500/20 text-red-400 border-red-500/30",
  Extreme: "bg-purple-500/20 text-purple-400 border-purple-500/30",
} as const;
